name: Build and Release

on:
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install `bun`
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
      
      - name: Calculate LOCs
        run: |
          npx cloc --git HEAD

      - name: Build project
        run: bun run compile

      - name: Upload JavaScript .map files for symbols
        uses: actions/upload-artifact@v4
        with:
          name: debug-lsp-routeros-ts-maps
          path: |
            *.map
            ./dist/*
            ./**/dist/*
            **/*.bun-build

      - name: Package VSIX
        run: |
          npm run vsix:package
          mv lsp-routeros-ts-*.vsix lsp-routeros-ts.vsix

      - name: Package standalone "bun exe" for the native platform of CI
        run: bun run compile:exe

      - name: Package cross-platform version of standalone LSP server
        run: |
          for i in bun-linux-x64 bun-linux-arm64 bun-darwin-x64 bun-darwin-arm64 bun-linux-x64-musl bun-linux-arm64-musl; do
            outname="${i#bun-}"
            bun build --compile ./server/src/server.ts --outfile ./lsp-routeros-server-$outname --target $i
            chmod 755 ./lsp-routeros-server-$outname
            zip ./lsp-routeros-server-$outname.zip ./lsp-routeros-server-$outname
          done

      - name: Package Windows version of standalone LSP server
        run: |
          bun build --compile ./server/src/server.ts --outfile ./lsp-routeros-server-windows-x64 --target bun-windows-x64
          ls -l ./lsp-routeros-server-windows-x64.exe
          chmod 755 ./lsp-routeros-server-windows-x64.exe
          ls -la
          zip ./lsp-routeros-server-windows-x64.zip ./lsp-routeros-server-windows-x64.exe

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: lsp-routeros-ts.vsix
          path: lsp-routeros-ts.vsix

      - name: Upload NeoVim Lua script artifact
        uses: actions/upload-artifact@v4
        with:
          name: nvim-routeros-lsp-init.lua
          path: nvim-routeros-lsp-init.lua

      - name: Upload lsp-routeros-server artifact for bun-linux-x64
        uses: actions/upload-artifact@v4
        with:
          name: lsp-routeros-server-linux-x64
          path: lsp-routeros-server-linux-x64.zip

      - name: Upload lsp-routeros-server artifact for bun-linux-arm64
        uses: actions/upload-artifact@v4
        with:
          name: lsp-routeros-server-linux-arm64
          path: lsp-routeros-server-linux-arm64.zip

      - name: Upload lsp-routeros-server artifact for bun-windows-x64
        uses: actions/upload-artifact@v4
        with:
          name: lsp-routeros-server-windows-x64.exe
          path: lsp-routeros-server-windows-x64.zip

      # disable - "bun-windows-arm64" target is failing, think it needs newer (or older) `bun` - requires investigation (and not easily testable)
      #- name: Upload lsp-routeros-server artifact for bun-windows-arm64
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: lsp-routeros-server-windows-arm64
      #    path: lsp-routeros-server-windows-arm64.zip

      - name: Upload lsp-routeros-server artifact for bun-darwin-x64
        uses: actions/upload-artifact@v4
        with:
          name: lsp-routeros-server-darwin-x64
          path: lsp-routeros-server-darwin-x64.zip

      - name: Upload lsp-routeros-server artifact for bun-darwin-arm64
        uses: actions/upload-artifact@v4
        with:
          name: lsp-routeros-server-darwin-arm64
          path: lsp-routeros-server-darwin-arm64.zip

      - name: Upload lsp-routeros-server artifact for bun-linux-x64-musl
        uses: actions/upload-artifact@v4
        with:
          name: lsp-routeros-server-linux-x64-musl
          path: lsp-routeros-server-linux-x64-musl.zip

      - name: Upload lsp-routeros-server artifact for bun-linux-arm64-musl
        uses: actions/upload-artifact@v4
        with:
          name: lsp-routeros-server-linux-arm64-musl
          path: lsp-routeros-server-linux-arm64-musl.zip

      - name: Get package version
        id: pkgver
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: v${{ steps.pkgver.outputs.version }}
          tag: v${{ steps.pkgver.outputs.version }}
          draft: false
          prerelease: true
          allowUpdates: true
          updateOnlyUnreleased: true
          body: |
            **LSP Server for RouterOS** (v${{steps.pkgver.outputs.version}})

            > [!NOTE]
            >
            > "Known Issues" and "Changelog" can be found in [CHANGELOG.md](https://github.com/tikoci/lsp-routeros-ts/blob/main/CHANGELOG.md).
            >
            > See [README.md](https://github.com/tikoci/lsp-routeros-ts/README.md) for more details about installation and usage.
            >

            For *VSCode*, download `lsp-routeros-ts.vsix` and install use `code --install-extension lsp-routeros-ts.vsix` from your download directory.

            For *NeoVim or other LSP clients*, download the specific `lsp-routeros-server-*` for your OS/platform, and copy to `~/.bin` (or another directory).
            A sample configuration file for NeoVim (`nvim`) , `nvim-routeros-lsp-init.lua`, is provided for download.

            > _Note about download file names..._
            > `darwin-` in name is for macOS, with `-arm64` is Apple Silicon while `-x64` is for Intel-based Mac platforms.
            > `-musl` in name is for Alpine Linux or some other specialized Linux distros.

          artifacts: |
            lsp-routeros-ts.vsix
            nvim-routeros-lsp-init.lua
            lsp-routeros-server-linux-x64.zip
            lsp-routeros-server-linux-arm64.zip
            lsp-routeros-server-windows-x64.zip
            lsp-routeros-server-darwin-x64.zip
            lsp-routeros-server-darwin-arm64.zip
            lsp-routeros-server-linux-x64-musl.zip
            lsp-routeros-server-linux-arm64-musl.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # TODO: Publish release should be it's own build task, VSCode works and Open-VSX should too
      #
      - name: Publish to VSCode Marketplace
        run: npx @vscode/vsce publish --no-dependencies -p ${{secrets.VSCE_PAT}}
      - name: Publish to Open-VSX too
        run: npx ovsx publish lsp-routeros-ts.vsix -p ${{secrets.OVSX_PAT}}
